### ISSUE TITLE
build 出现错误, windows 下路径出现出现 ： 字符

### ISSUE THREAD

**Issue by chwang98** [Xutaotaotao/electron-prokit#49]
```
C:\Users\wang\AppData\Roaming\npm\pnpm.cmd run compile

> play@1.0.0 compile D:\dev\person\electron-prokit\play
> electron-builder build --config ./electron-builder.config.ts

  • electron-builder  version=24.6.4 os=10.0.22631
compiling: [
  'D:\\dev\\person\\electron-prokit\\play\\electron-builder.config.ts'
]
Could not write file 'C:/Users/wang/.cache/config-file-ts/:-dev-person-electron-prokit-play-electron-builder.config.ts/dev/person/electron-prokit/play/electron-builder.config.js': EINVAL: invalid argument, mkdir 'C:/Users/wang/.cache/config-file-ts/:-dev-person-electron-prokit-play-electron-builder.config.ts'.
  ⨯ ENOENT: no such file or directory, open 'C:\Users\wang\.cache\config-file-ts\:-dev-person-electron-prokit-play-electron-builder.config.ts\_sources'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, open 'C:\Users\wang\.cache\config-file-ts\:-dev-person-electron-prokit-play-electron-builder.config.ts\_sources'
    at Object.openSync (node:fs:603:3)
    at Object.writeFileSync (node:fs:2324:35)
    at saveExtendedSources (D:\dev\person\electron-prokit\node_modules\.pnpm\config-file-ts@0.2.4\node_modules\config-file-ts\src\compileUtil.ts:98:6)
    at compileIfNecessary (D:\dev\person\electron-prokit\node_modules\.pnpm\config-file-ts@0.2.4\node_modules\config-file-ts\src\compileUtil.ts:74:7)
    at compileConfigIfNecessary (D:\dev\person\electron-prokit\node_modules\.pnpm\config-file-ts@0.2.4\node_modules\config-file-ts\src\compileUtil.ts:173:19)
    at Object.loadTsConfig (D:\dev\person\electron-prokit\node_modules\.pnpm\config-file-ts@0.2.4\node_modules\config-file-ts\src\loadTsConfig.ts:18:20)
    at readConfig (D:\dev\person\electron-prokit\node_modules\.pnpm\read-config-file@6.3.2\node_modules\read-config-file\src\main.ts:30:14)
    at getConfig (D:\dev\person\electron-prokit\node_modules\.pnpm\app-builder-lib@24.6.4\node_modules\app-builder-lib\src\util\config.ts:44:34)
    at Packager.build (D:\dev\person\electron-prokit\node_modules\.pnpm\app-builder-lib@24.6.4\node_modules\app-builder-lib\src\packager.ts:314:27)
    at executeFinally (D:\dev\person\electron-prokit\node_modules\.pnpm\builder-util@24.5.0\node_modules\builder-util\src\promise.ts:12:14)
 ELIFECYCLE  Command failed with exit code 1.

进程已结束，退出代码为 1

```

上面的是控制台信息

**Comment by Xutaotaotao** [comment]
看着好像是权限问题

**Comment by chwang98** [comment]
> 看着好像是权限问题
> 

Windows的文件路径是不能出现冒号，我不知道这个路径是在哪里生成的

**Comment by wrcoldsix** [comment]
我这也是类似的问题，怎么解决的

**Comment by chwang98** [comment]
> 我这也是类似的问题，怎么解决的

没解决，我换了这个[https://github.com/electron-react-boilerplate/electron-react-boilerplate](https://github.com/Xutaotaotao/electron-prokit/issues/url)
