### ISSUE TITLE
compile 打包的时候遇到这个问题。请问有什么解决办法。

### ISSUE THREAD

**Issue by boyGdm** [Xutaotaotao/electron-prokit#53]
electron-builder  version=24.13.3 os=10.0.22631
compiling: [ 'D:\\code\\electron\\Demo\\myapp\\electron-builder.config.ts' ]
Could not write file 'C:/Users/xqx/.cache/config-file-ts/:-code-electron-Demo-myapp-electron-builder.config.ts/code/electron/Demo/myapp/electron-builder.config.js': EINVAL: invalid argument, mkdir 'C:/Users/xqx/.cache/config-file-ts/:-code-electron-Demo-myapp-electron-builder.config.ts'.
  ⨯ ENOENT: no such file or directory, open 'C:\Users\xqx\.cache\config-file-ts\:-code-electron-Demo-myapp-electron-builder.config.ts\_sources'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, open 'C:\Users\xqx\.cache\config-file-ts\:-code-electron-Demo-myapp-electron-builder.config.ts\_sources'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2155:35)
    at saveExtendedSources (D:\code\electron\Demo\myapp\node_modules\.pnpm\config-file-ts@0.2.6\node_modules\config-file-ts\src\compileUtil.ts:98:6)
    at compileIfNecessary (D:\code\electron\Demo\myapp\node_modules\.pnpm\config-file-ts@0.2.6\node_modules\config-file-ts\src\compileUtil.ts:74:7)
    at compileConfigIfNecessary (D:\code\electron\Demo\myapp\node_modules\.pnpm\config-file-ts@0.2.6\node_modules\config-file-ts\src\compileUtil.ts:172:19)
    at Object.loadTsConfig (D:\code\electron\Demo\myapp\node_modules\.pnpm\config-file-ts@0.2.6\node_modules\config-file-ts\src\loadTsConfig.ts:18:20)
    at readConfig (D:\code\electron\Demo\myapp\node_modules\.pnpm\read-config-file@6.3.2\node_modules\read-config-file\src\main.ts:30:14)
    at getConfig (D:\code\electron\Demo\myapp\node_modules\.pnpm\app-builder-lib@24.13.3_dmg-builder@24.13.3_electron-builder-squirrel-windows@24.13.3\node_modules\app-builder-lib\src\util\config.ts:44:34)
    at Packager.build (D:\code\electron\Demo\myapp\node_modules\.pnpm\app-builder-lib@24.13.3_dmg-builder@24.13.3_electron-builder-squirrel-windows@24.13.3\node_modules\app-builder-lib\src\packager.ts:317:27)
    at Object.loadTsConfig (D:\code\electron\Demo\myapp\node_modules\.pnpm\config-file-ts@0.2.6\node_modules\config-file-ts\src\loadTsConfig.ts:18:20)
    at readConfig (D:\code\electron\Demo\myapp\node_modules\.pnpm\read-config-file@6.3.2\node_modules\read-config-file\src\main.ts:30:14)
    at getConfig (D:\code\electron\Demo\myapp\node_modules\.pnpm\app-builder-lib@24.13.3_dmg-builder@24.13.3_electron-builder-squirrel-windows@24.13.3\node_modules\app-builder-lib\src\util\config.ts:44:34)
    at Packager.build (D:\code\electron\Demo\myapp\node_modules\.pnpm\app-builder-lib@24.13.3_dmg-builder@24.13.3_electron-builder-squirrel-windows@24.13.3\node_modules\app-builder-lib\src\packager.ts:317:27)
    at executeFinally (D:\code\electron\Demo\myapp\node_modules\.pnpm\builder-util@24.13.1\node_modules\builder-util\src\promise.ts:12:14)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by boyGdm** [comment]
![image](https://github.com/Xutaotaotao/electron-prokit/assets/28535569/36c44354-6e5a-491e-996c-55186fbc29b5)

**Comment by Peng88811** [comment]
我也遇到了，windows11，GPT回复的是：这个错误是在尝试使用 electron-builder 编译 TypeScript 配置文件时发生的。问题的根源在于文件系统操作，具体是因为尝试创建一个包含非法字符的目录。

错误消息指出，系统无法在路径 C:\Users\Administrator\.cache\config-file-ts\:-project-template-react-ts-electron-builder.config.ts 下创建目录或写入文件。在 Windows 文件系统中，路径名中的冒号 : 是不允许的，因为它是为驱动器标签（如 C:）保留的。

**Comment by Xutaotaotao** [comment]
是在什么情况下compile的呢？可以给出复现的步骤吗？我看看用windows电脑是否能复现这个场景

**Comment by Peng88811** [comment]
![image](https://github.com/Xutaotaotao/electron-prokit/assets/92702721/91a3b927-8ebb-4d99-a9a2-ec25f01bb54e)


图中是项目结构，使用的是template-react-ts，并且图中也有node版本号，运行："compile": "electron-builder build --config ./electron-builder.config.ts",就会报楼主的错误

**Comment by Peng88811** [comment]
"C:\Program Files\nodejs\yarn.cmd" run compile
yarn run v1.22.22
warning package.json: "test" is also the name of a node core module
$ electron-builder build --config ./electron-builder.config.ts
  • electron-builder  version=24.13.3 os=10.0.22631
compiling: [ 'D:\\project\\template-react-ts\\electron-builder.config.ts' ]
Could not write file 'C:/Users/Administrator/.cache/config-file-ts/:-project-template-react-ts-electron-builder.config.ts/project/template-react-ts/electron-builder.config.js': EINVAL: invalid argument, mkdir 'C:\Users\Administrator\.cache\config-file-ts\:-project-template-react-ts-electron-builder.config.ts'.
  ⨯ ENOENT: no such file or directory, open 'C:\Users\Administrator\.cache\config-file-ts\:-project-template-react-ts-electron-builder.config.ts\_sources'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\.cache\config-file-ts\:-project-template-react-ts-electron-builder.config.ts\_sources'
    at Object.writeFileSync (node:fs:2342:20)
    at saveExtendedSources (D:\project\template-react-ts\node_modules\config-file-ts\src\compileUtil.ts:98:6)
    at compileIfNecessary (D:\project\template-react-ts\node_modules\config-file-ts\src\compileUtil.ts:74:7)
    at compileConfigIfNecessary (D:\project\template-react-ts\node_modules\config-file-ts\src\compileUtil.ts:172:19)
    at Object.loadTsConfig (D:\project\template-react-ts\node_modules\config-file-ts\src\loadTsConfig.ts:18:20)
    at readConfig (D:\project\template-react-ts\node_modules\read-config-file\src\main.ts:30:14)
    at getConfig (D:\project\template-react-ts\node_modules\app-builder-lib\src\util\config.ts:44:34)
    at Packager.build (D:\project\template-react-ts\node_modules\app-builder-lib\src\packager.ts:317:27)
    at executeFinally (D:\project\template-react-ts\node_modules\builder-util\src\promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

进程已结束,退出代码1

**Comment by Xutaotaotao** [comment]
> ![image](https://private-user-images.githubusercontent.com/92702721/330019049-91a3b927-8ebb-4d99-a9a2-ec25f01bb54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk0MjcsIm5iZiI6MTcxNTU5OTEyNywicGF0aCI6Ii85MjcwMjcyMS8zMzAwMTkwNDktOTFhM2I5MjctOGViYi00ZDk5LWE5YTItZWMyNWYwMWJiNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExMTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMjQ4MzkzNTMxN2I0M2MyZjMyOGIwMzM0NzA1N2I4MzQxMDYzYzg4NDk4NzZlMDM0ZWYxNjBjZjI2Y2RmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VZTVXv616urociehh4O2oXR-RPbOCWAMY5RXFBYZ_I0)
> 
> 图中是项目结构，使用的是template-react-ts，并且图中也有node版本号，运行："compile": "electron-builder build --config ./electron-builder.config.ts",就会报楼主的错误

你是直接 用脚手架创建的代码还是直接用的源码里的template-react-ts目录

**Comment by Peng88811** [comment]
源码里的下载的压缩包

**Comment by Xutaotaotao** [comment]
> 源码里的下载的压缩包

OK，我抽空看下

**Comment by boyGdm** [comment]
@Xutaotaotao  源码和 用脚手架创建的都是同样的问题。我试过了。   还有设置 webPreferences.contextIsolation =false  的时候，渲染进程 会报  Uncaught TypeError: path.join is not a function。楼主有空也一并处理一下。

**Comment by Xutaotaotao** [comment]
> @Xutaotaotao 源码和 用脚手架创建的都是同样的问题。我试过了。 还有设置 webPreferences.contextIsolation =false 的时候，渲染进程 会报 Uncaught TypeError: path.join is not a function。 楼主有空也一并处理一下。

https://www.electronjs.org/docs/latest/tutorial/security

这个框架没有开启node集成(nodeIntegration)和关闭上下文隔离(contentIsolation)，框架内部的方法都是用contextBridge实现的。

**Comment by Pone-Li** [comment]
我現在還是這個問題 沒有解決嗎

**Comment by Xutaotaotao** [comment]
> 我現在還是這個問題 沒有解決嗎

最新版本还有问题吗

**Comment by fengybl** [comment]
最新版任然有这个问题,请帮忙解决

**Comment by Xutaotaotao** [comment]
> 最新版任然有这个问题,请帮忙解决

看看具体的报错，以及环境，操作步骤
