### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Turnip1202** [Xutaotaotao/electron-prokit#57]
Environment: **Windows11 x64，AMD Ryzen 7 8845H w/ Radeon 780M Graphics   3.80 GHz，Node.js:v20.18.0**
# error message：

turni@kang MINGW64 /d/ACode/Code_test/demo/vite-react-app-ts-electron
$ npm run compile

> vite-react-app-ts-electron@1.0.0 compile
> electron-builder build --config ./electron-builder.config.ts

  • electron-builder  version=24.13.3 os=10.0.22631
compiling: [
  'D:\\ACode\\Code_test\\demo\\vite-react-app-ts-electron\\electron-builder.config.ts'
]
Could not write file 'C:/Users/turni/.cache/config-file-ts/:-ACode-Code_test-demo-vite-react-app-ts-electron-electron-builder.config.ts/ACode/Code_test/demo/vite-react-app-ts-electron/electron-builder.config.js': EINVAL: invalid argument, mkdir 'C:\Users\turni\.cache\config-file-ts\:-ACode-Code_test-demo-vite-react-app-ts-electron-electron-builder.config.ts'.
  ⨯ ENOENT: no such file or directory, open 'C:\Users\turni\.cache\config-file-ts\:-ACode-Code_test-demo-vite-react-app-ts-electron-electron-builder.config.ts\_sources'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, open 'C:\Users\turni\.cache\config-file-ts\:-ACode-Code_test-demo-vite-react-app-ts-electron-electron-builder.config.ts\_sources'
    at Object.writeFileSync (node:fs:2367:20)
    at saveExtendedSources (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\config-file-ts@0.2.6\node_modules\config-file-ts\src\compileUtil.ts:98:6)
    at compileIfNecessary (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\config-file-ts@0.2.6\node_modules\config-file-ts\src\compileUtil.ts:74:7)
    at compileConfigIfNecessary (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\config-file-ts@0.2.6\node_modules\config-file-ts\src\compileUtil.ts:172:19)
    at Object.loadTsConfig (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\config-file-ts@0.2.6\node_modules\config-file-ts\src\loadTsConfig.ts:18:20)
    at readConfig (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\read-config-file@6.3.2\node_modules\read-config-file\src\main.ts:30:14)
    at getConfig (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\app-builder-lib@24.13.3\node_modules\app-builder-lib\src\util\config.ts:44:34)
    at Packager.build (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\app-builder-lib@24.13.3\node_modules\app-builder-lib\src\packager.ts:317:27)
    at executeFinally (D:\ACode\Code_test\demo\vite-react-app-ts-electron\node_modules\.store\builder-util@24.13.1\node_modules\builder-util\src\promise.ts:12:14)

## Project directory tree
D:\ACode\Code_test\demo\vite-react-app-ts-electron
├── .eslintrc.cjs
├── config
|  ├── main.ts
|  ├── preload.ts
|  ├── render.ts
|  └── work.ts
├── dist
|  ├── main
|  |  └── index.cjs
|  ├── preload
|  |  └── index.cjs
|  ├── render
|  |  ├── assets
|  |  |  ├── index-6a367acc.js
|  |  |  ├── index-907cee70.css
|  |  |  └── logo-8251e29a.svg
|  |  ├── index.html
|  |  └── vite.svg
|  └── work
|     ├── assets
|     |  └── index-f0de7251.js
|     └── index.html
├── electron-builder.config.ts
├── index.html
├── out.txt
├── package.json
├── public
|  └── vite.svg
├── README.md
├── resources
|  └── icon
|     ├── icon.icns
|     ├── icon.ico
|     ├── icon.png
|     └── icon@2x.png
├── scripts
|  ├── build.ts
|  ├── dev.ts
|  └── entitlements.mac.plist
├── src
|  ├── main
|  |  ├── index.ts
|  |  └── ipc.ts
|  ├── preload
|  |  └── index.ts
|  ├── render
|  |  ├── App.css
|  |  ├── App.tsx
|  |  ├── assets
|  |  |  ├── logo.svg
|  |  |  └── react.svg
|  |  ├── index.css
|  |  ├── main.tsx
|  |  └── vite-env.d.ts
|  ├── type.d.ts
|  ├── util
|  |  └── index.ts
|  └── work
|     ├── App.tsx
|     ├── index.html
|     └── main.tsx
└── tsconfig.json

directory: 1169 file: 2444 symboliclink: 907

ignored: directory (524)

# package.json
{
  "name": "vite-react-app-ts-electron",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "description": "a react app.",
  "author": "Turnip",
  "main": "dist/main/index.cjs",
  "scripts": {
    "dev": "node --experimental-specifier-resolution=node --loader ts-node/esm ./scripts/dev.ts",
    "build": "node --experimental-specifier-resolution=node --loader ts-node/esm ./scripts/build.ts",
    "compile": "electron-builder build --config ./electron-builder.config.ts",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "koffi": "2.3.20"
  },
  "devDependencies": {
    "@electron-prokit/create-service": "^3.0.0",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react-swc": "^3.3.2",
    "electron": "^26.2.0",
    "electron-builder": "^24.6.4",
    "eslint": "^8.45.0",
    "electron-prokit": "^16.1.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}

**Comment by Xutaotaotao** [comment]
命令行初始化一下最新的项目试试看，应该已经修复了
